### ISSUE TITLE
Does not work when using OnPush Change Detection Strategy

### ISSUE THREAD

**Issue by pavankjadda** [ngneat/loadoff#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Spinner/Loader does not hide after change in the status when using with OnPush Change Detection Strategy

## Expected behavior
Spinner/Loader hides as expected

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-khicoc?file=src%2Fapp%2Fapp.component.ts

## Environment
Angular version: 13.3.5

Browser:
- [x] Chrome (desktop) version 101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
You need to create a new instance:

```ts
    setTimeout(() => {
      this.state = createAsyncState({ loading: true }); 
    }, 3000);
```

**Comment by pavankjadda** [comment]
> You need to create a new instance:
> 
> ```ts
>     setTimeout(() => {
>       this.state = createAsyncState({ loading: true }); 
>     }, 3000);
> ```

I did that but still does not hide the loader. You can see the updated [example](https://stackblitz.com/edit/angular-ivy-khicoc?file=src%2Fapp%2Fapp.component.ts)

**Comment by NetanelBasal** [comment]
That's not related to the library. Read about onPush, please.

https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4
