### ISSUE TITLE
Feature request: Keep value 

### ISSUE THREAD

**Issue by Waterstraal** [ngneat/loadoff#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The value is discarded on a new emission. This is not always the desired behavior, for example when you want to implement reload functionality where you want to keep showing the current items while you fetch fresh items in the background. 

## Expected behavior

The value is persisted. 

## Minimal reproduction of the problem with instructions

I created a stackblitz with a workaround for above problem:
https://stackblitz.com/edit/loadoff-keep-value-on-reload?file=src%2Fapp%2Fhello.component.ts

## What is the motivation / use case for changing the behavior?

I feel like it's a common use case and it would be nice if the library would support it out of the box.

**Comment by NetanelBasal** [comment]
Do u want to submit a PR?

**Comment by Waterstraal** [comment]
@NetanelBasal I have created a PR
