### ISSUE TITLE
Feature request: toAsyncState pipe

### ISSUE THREAD

**Issue by Waterstraal** [ngneat/loadoff#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is no pipe, so all the mapping should be done in the component. 

## Expected behavior

There is a pipe which you can use in templates

## Minimal reproduction of the problem with instructions

I created a stackblitz with a toAsyncState pipe: 

https://stackblitz.com/edit/loadoff-toasyncstate-pipe?file=src%2Fapp%2Fhello.component.ts

```
@Pipe({
  name: "toAsyncState"
})
export class ToAsyncStatePipe implements PipeTransform {
  transform<T>(val: Observable<T>): Observable<AsyncState<T>> {
    return isObservable(val) ? val.pipe(toAsyncState<T>()) : val;
  }
}
```

## What is the motivation / use case for changing the behavior?

The code would be a bit cleaner for simple use cases.

**Comment by NetanelBasal** [comment]
Do u want to submit a PR?

**Comment by NetanelBasal** [comment]
I'm closing this request as it'll make the library coupled to Angular, and it doesn't worth it for one line of code. Users can easily add it to the application if they want this functionality.
