### ISSUE TITLE
Feature request: provide anyLoading operator

### ISSUE THREAD

**Issue by timfaase** [ngneat/loadoff#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

It would be nice to have a loading operator that combines loading from multiple streams.

## Expected behavior

There is an operator that extracts a loading indicator for provided AsyncState streams.

## Minimal reproduction of the problem with instructions

Could look like this; 
<pre><code>
export function anyLoading(): (source: Observable<AsyncState<any>[]>) => Observable<boolean> {
  return (source: Observable<AsyncState<any>[]>): Observable<boolean> =>
    source.pipe(map((values: AsyncState<any>[]) => values.some((el: AsyncState<any>) => el.loading)));
}
</code></pre>

Usage: 
<pre><code>
loading$: Observable<boolean> = combineLatest([stream1$, stream2$]).pipe(anyLoading());
</code></pre>

## What is the motivation / use case for changing the behavior?

Just a convenience operator.

**Comment by NetanelBasal** [comment]
Can you explain the use case, please?

**Comment by timfaase** [comment]
We have multiple streams that are loading and we want to show a loading state in some parts of the application that depend on multiple streams of which either one or both can be loading.

The results of those streams however are then separately used.

**Comment by NetanelBasal** [comment]
I don't know if this is a common use case, so I'll wait for more feedback. In the meantime, you can use the code you suggested. Thanks.

**Comment by martinobordin** [comment]
I have a similar requirement and I think it's pretty common:
a component that is showing a form and must perform several http requests on the init phase:
1 to load the data to edit and 2\3 to load the data to show in different select controls.
