### ISSUE TITLE
After first loading, loading value doesn't change

### ISSUE THREAD

**Issue by bmarvinb** [ngneat/loadoff#7]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using to toAsyncState, and I struggle with one problem, after first loading, it is not working as expected, I make requests, but the loading property didn't change, it works only in the first time when data is not loaded.

## Expected behavior

Loading should be true every time when user make a request

## Minimal reproduction of the problem with instructions
Try to reload some data, after it was loaded the first time

**Comment by NetanelBasal** [comment]
See the examples in the playground - https://github.com/ngneat/loadoff/blob/master/src/app/app.component.ts
